# Generated by Django 3.0.7 on 2021-06-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, choices=[('M', 'Camisa Mujer'), ('H', 'Camisa Varon')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Iniciada', 'Iniciada'), ('Terminada', 'Terminada'), ('Reintegrada', 'Reintegrada')], default='Iniciada', max_length=64),
        ),
    ]
